## create a single pod to test pull from dockerhub 

apiVersion: v1
kind: Pod
metadata:
  name: httpserver
spec:
  containers:
    - name: httpserver
      image: oliverzhang17/httpserver:0.2
      ports:
        - containerPort: 80